# Generated by Django 3.0 on 2021-01-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazardous',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=10)),
                ('city', models.CharField(max_length=50)),
                ('severity_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('incidents_total', models.IntegerField()),
            ],
            options={
                'ordering': ('-incidents_total',),
            },
        ),
    ]
