# Generated by Django 3.0 on 2021-01-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarkSpots',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=10)),
                ('city', models.CharField(max_length=50)),
                ('avg_drops', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percent_affected', models.IntegerField()),
            ],
            options={
                'ordering': ('-percent_affected', '-avg_drops'),
            },
        ),
    ]
