// Auth
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERR = "SIGNUP_ERR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERR = "SIGNIN_ERR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERR = "SIGNOUT_ERR";
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_ERR = 'AUTHENTICATED_ERR';

// Profile
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERR = 'LOAD_PROFILE_ERR';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERR = 'UPDATE_PROFILE_ERR';