# Generated by Django 3.1.5 on 2021-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=3)),
                ('expiry', models.DateField(blank=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('is_donation', models.BooleanField()),
                ('location', models.CharField(max_length=50)),
                ('is_weekday', models.BooleanField()),
                ('time', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donor', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
            ],
        ),
    ]
