# Generated by Django 3.1.5 on 2021-01-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210109_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_arriving',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_shipping',
        ),
    ]
